### ISSUE TITLE
Tests stucks on "load generators preparation step"

### ISSUE THREAD

**Issue by AalimahG** [Neotys-Labs/neoload-cli#223]
I did neoload web install on kubernetes with helm with license activated.
Environment:
-AKS
- Mongodb M50

Dynamic infrastructure tests return the following error at the pod level ( controller and generator dynamically provisioned ):
```
[async-channel-group-0-handler-executor] ERROR c.n.w.w.MongoTasksCoordinatorService - Unhandled error occurred w
hile polling getTask: ImmutableTask{name=do-lg-resource-election-task, visibilityTimeoutInS=60, dequeueTimeoutInMs=500, retryCount=10, r
etryDelayInS=2} at WorkflowAddress{databaseName=neoload-web, workflowName=bench-start-bench-runtime-v1}

```
Do you have any leads

**Comment by guillaumebert** [comment]
This issue is not related to the NeoLoad CLI.
You can also read the [documentation about dynamic infrastructure](https://documentation.tricentis.com/nlweb/latest/en/content/user_guides/dynamic_infrastructure.htm?Highlight=dynamic) to make sure you configured everything properly.

If you need help, please contact the Tricentis Implementation Team that should assist you when installing NeoLoad web Onpremise, or contact the support via the [support hub](https://support-hub.tricentis.com/).
